openai_key: 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
openai_platform_key: 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
default_data_dir: /Users/jianhuang/data
api_function_dir: _api._function
git_token: Z2hwXzc5T3JuaVNjMEVRRzlKU2I0cnBIREY0bHZDRTFwZTJzdUFqaA==